metric: COCO
num_classes: 80

# Datset configuration
EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco_val2017/

# TestDataset:
#   !COCODataSet
#     image_dir: val2017
#     anno_path: annotations/instances_val2017.json
#     dataset_dir: dataset/coco

TestDataset:
  !COCODataSet
    image_dir: images
    anno_path: val.json
    dataset_dir: dataset/coco_mini/val

worker_num: 1

# preprocess reader in test
EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
